#!/usr/bin/env bash

OPTS="$( getopt -ao "r" -l "refresh" -- "${@}" )"

[[ "${?}" != 0 ]] && exit 1

eval set -- "${OPTS}"
unset OPTS

REFRESH=false

while true; do
	case "${1}" in
		"-r" | "--refresh" )
			REFRESH=true
			shift
			;;
		"--" )
			shift
			break
			;;
		* )
			break
			;;
	esac
done

RED="^c#d20f39^"
YLW="^c#df8e1d^"
GRN="^c#40a02b^"
BLU="^c#1e66f5^"
NC="^c#cdd6f4^"

BT() {
	CAP="$(cat /sys/class/power_supply/BAT0/capacity)"
	STAT="$(cat /sys/class/power_supply/BAT0/status)"

	PREFIX="u"
	[[ "${STAT}" = "Charging" ]] && PREFIX="c"

	if (( $CAP >= 60 )); then
		PREFIX="${GRN}${PREFIX}${NC}"
	elif (( $CAP >= 30 )); then
		PREFIX="${YLW}${PREFIX}${NC}"
	else
		PREFIX="${RED}${PREFIX}${NC}"
	fi

	printf "%s %s%%" "BT" "${PREFIX}${CAP}"
}

BR() {
	BRT="$( calc -d "100 * $( brightnessctl get ) / $( brightnessctl max )" )"
	BRT="$( printf "%.0f" "$( echo "scale=2;${BRT}" | bc )" )"

	printf "%s %s%%" "BR" "${BRT}"
}

WF() {
	case "$( cat /sys/class/net/wl*/operstate 2> /dev/null )" in
		"up" )
			STAT="${BLU}up${NC}"
			;;
		"down" )
			STAT="${RED}dn${NC}"
			;;
	esac

	printf "%s %s" "WF" "${STAT}"
}

VL() {
	MUTE="$( pactl get-sink-mute @DEFAULT_SINK@ )"
	VOL="$( pactl get-sink-volume @DEFAULT_SINK@ \
		| grep "Volume:" | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' )"

	PREFIX="u"
	if [[ "${MUTE}" = "Mute: yes" ]]; then
		PREFIX="${RED}m${NC}"
	elif [[ "${VOL}" = "0" ]]; then
		PREFIX="${YLW}${PREFIX}${NC}"
	else
		PREFIX="${GRN}${PREFIX}${NC}"
	fi

	test -z "${VOL}" && VOL="${YLW}-loading-${NC}" && PREFIX=""

	printf "%s %s%%" "VL" "${PREFIX}${VOL}"
}

if [[ "${REFRESH}" = false ]]; then
	echo -n " $(VL) | $(BR) | $(BT) | $(WF) | $(date '+%b %d %a %R') "
else
	PID="$( cat "${DWM_SLEEP_PID}" | tr -d '\n' )"
	test -n "${PID}" && kill -KILL "${PID}"
fi
