#!/usr/bin/env bash

OPTS=$(getopt -ao 'udml:s:' -l 'up,down,mute,level:,set:' -- "$@" )

[[ $? != 0 ]] && exit 1

eval set -- "$OPTS"
unset OPTS

UP=true
DOWN=false
MUTE=false
LEVEL=4
SET=0

while true; do
	case $1 in
		-u|--up)
			UP=true
			DOWN=false
			shift
			;;
		-d|--down)
			DOWN=true
			UP=false
			shift
			;;
		-m|--mute)
			MUTE=true
			shift
			;;
		-l|--level)
			LEVEL=$2
			shift 2
			;;
		-s|--set)
			SET=$2
			shift 2
			;;
		--)
			shift
			break
			;;
		*)
			exit 1
			;;
	esac
done

command -v pactl &> /dev/null || exit 127

unmute() {
	pactl set-sink-mute 0 0
}

if [[ ! $SET -eq 0 ]]; then
	pactl set-sink-volume 0 "$SET%" && unmute
elif [[ $MUTE == true ]]; then
	pactl set-sink-mute 0 toggle
elif [[ $DOWN == true ]]; then
	pactl set-sink-volume 0 "-$LEVEL%" && unmute
elif [[ $UP == true ]]; then
	pactl set-sink-volume 0 "+$LEVEL%" && unmute
fi

if test -x "$DF_SCRIPTS_DIR"/status; then
	"$DF_SCRIPTS_DIR"/status -r
fi

exit 0
