#!/usr/bin/env bash

OPTS=$(getopt -ao 'udl:s:' -l 'up,down,level:,set:' -- "$@")

[[ $? != 0 ]] && exit 1

eval set -- "$OPTS"
unset OPTS

UP=true
DOWN=false
LEVEL=5
SET=0

while true; do
	case $1 in
		-u|--up)
			UP=true
			DOWN=false
			shift
			;;
		-d|--down)
			DOWN=true
			UP=false
			shift
			;;
		-l|--level)
			LEVEL=$2
			shift 2
			;;
		-s|--set)
			SET=$2
			shift 2
			;;
		--)
			shift
			break
			;;
		*)
			exit 1
			;;
	esac
done

command -v brightnessctl &> /dev/null || exit 127

if [[ ! $SET -eq 0 ]]; then
	brightnessctl --quiet set "$SET%"
elif [[ $UP == true ]]; then
	brightnessctl --quiet set "+$LEVEL%"
elif [[ $DOWN == true ]]; then
	brightnessctl --quiet set "$LEVEL-%"
fi

if test -x "$HOME/.dotfiles/scripts/status"; then
	sh -c "$HOME/.dotfiles/scripts/status -r"
fi

exit 0
