#!/usr/bin/env bash

command -v yt-dlp &> /dev/null || exit 127

URL=$(xclip -selection clipboard -out 2> /dev/null)
DIR=${XDG_MUSIC_DIR:-$HOME/mc/}

[[ "$URL" != *https*youtube*watch* ]] && exit 1

yt-dlp --extract-audio --audio-format 'opus' --audio-quality 0 \
	--no-playlist --paths "$DIR" "$URL"

exit 0
