#!/usr/bin/env sh

{
	sleep 4s
	while true; do
		xsetroot -name "$("$DF_SCRIPTS_DIR"/status)"
		sleep 1m &
		echo "$!" > "$DWM_SLEEP_PID"
		wait $!
	done
} &

xrandr --size 1920x1080 &

xset s off -dpms &

# FIXME: It locks when watching videos.
# xautolock -time 10 -locker slock &

xset r rate 350 55 &

command -v xbanish &> /dev/null && xbanish -i mod4 &

setxkbmap -layout 'us,ua' -option 'grp:shifts_toggle' &

if [ -f "$XDG_CONFIG_HOME/sxhkd/sxhkdrc" ]; then
	sxhkd -c "$XDG_CONFIG_HOME/sxhkd/sxhkdrc"
fi &

xinput set-prop 'Synaptics TM3336-001' 'libinput Tapping Enabled' 1 &

if [ -e "$XDG_DATA_HOME/wallpapers/default" ]; then
	feh --no-fehbg --bg-scale "$XDG_DATA_HOME/wallpapers/default"
fi &

exec dwm
