#!/usr/bin/env sh

{
	sleep 4s
	while true; do
		xsetroot -name "$( sh -c "${HOME}/.scripts/dwm/status.sh -p" )"
		sleep 1m &
		echo -n "${!}" > "${DWM_SLEEP_PID}"
		wait "${!}"
	done
} &

xrandr --size 1920x1080 &

xset r rate 350 55 &

xset s off -dpms &

unclutter --exclude-root --timeout 5 &

xinput set-prop "Synaptics TM3336-001" "libinput Tapping Enabled" 1 &

setxkbmap -layout "us,ua" -option "grp:shifts_toggle" &

if [ -f "${XDG_CONFIG_HOME}/sxhkd/sxhkdrc" ]; then
	sxhkd -c "${XDG_CONFIG_HOME}/sxhkd/sxhkdrc"
fi &

if [ -e "${XDG_DATA_HOME}/wallpapers/default" ]; then
	feh --no-fehbg --bg-scale "${XDG_DATA_HOME}/wallpapers/default"
fi &

exec dwm
